CREATE TABLE CITY (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR, STATE VARCHAR, COUNTRY VARCHAR);

INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('SAN FRANCISCO', 'CA', 'US');
INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('XI AN', 'CA', 'CH');
INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('TOKYO', 'CA', 'JAPAN');
INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('SEOUL', 'CA', 'KOREA');
INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('LONDON', 'CA', 'UK');
